//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ecatalog.ConsoleApp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ecatalog.ConsoleApp.LocalizedStrings", typeof(LocalizedStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a book to the catalog, you must specify all the fields.
        /// </summary>
        internal static string AddMandatory {
            get {
                return ResourceManager.GetString("AddMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string AnswerYes {
            get {
                return ResourceManager.GetString("AnswerYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the author first name:.
        /// </summary>
        internal static string AskAuthorFirstName {
            get {
                return ResourceManager.GetString("AskAuthorFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the author last name:.
        /// </summary>
        internal static string AskAuthorLastName {
            get {
                return ResourceManager.GetString("AskAuthorLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the author note:.
        /// </summary>
        internal static string AskAuthorNote {
            get {
                return ResourceManager.GetString("AskAuthorNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the book rating (from 1 to 4):.
        /// </summary>
        internal static string AskBookRating {
            get {
                return ResourceManager.GetString("AskBookRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the full path to the file (for example c:\Test\test.dat).
        /// </summary>
        internal static string AskDatFilePathAndName {
            get {
                return ResourceManager.GetString("AskDatFilePathAndName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add one more author? Enter &quot;Yes&quot; for it.
        /// </summary>
        internal static string AskForAddAuthor {
            get {
                return ResourceManager.GetString("AskForAddAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the ISBN code of the book (GUID format only):.
        /// </summary>
        internal static string AskISBN {
            get {
                return ResourceManager.GetString("AskISBN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the full path to the file (for example c:\Test\test.json).
        /// </summary>
        internal static string AskJsonFilePathAndName {
            get {
                return ResourceManager.GetString("AskJsonFilePathAndName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the language in which the book is written:.
        /// </summary>
        internal static string AskLanguage {
            get {
                return ResourceManager.GetString("AskLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the name of the book:.
        /// </summary>
        internal static string AskName {
            get {
                return ResourceManager.GetString("AskName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the programming language that is described in the book:.
        /// </summary>
        internal static string AskProgrammingLanguage {
            get {
                return ResourceManager.GetString("AskProgrammingLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the difficulty level for the reader (1 to 3):.
        /// </summary>
        internal static string AskReaderLevel {
            get {
                return ResourceManager.GetString("AskReaderLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify the full path to the file (for example c:\Test\test.xml).
        /// </summary>
        internal static string AskXmlFilePathAndName {
            get {
                return ResourceManager.GetString("AskXmlFilePathAndName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the year the book was published:.
        /// </summary>
        internal static string AskYearOfPublication {
            get {
                return ResourceManager.GetString("AskYearOfPublication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The book added to the catalog.
        /// </summary>
        internal static string BookAdded {
            get {
                return ResourceManager.GetString("BookAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The book has deleted from the catalog.
        /// </summary>
        internal static string BookDeleted {
            get {
                return ResourceManager.GetString("BookDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes on the book are made to the catalog.
        /// </summary>
        internal static string BookEdited {
            get {
                return ResourceManager.GetString("BookEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From the catalog downloaded books in the amount of:.
        /// </summary>
        internal static string BookRetrieved {
            get {
                return ResourceManager.GetString("BookRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the language code (&apos;ru&apos;, or &apos;en&apos;) to change it:.
        /// </summary>
        internal static string ChooseLanguage {
            get {
                return ResourceManager.GetString("ChooseLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the command to continue:
        ///Add - add a new book to the catalog,
        ///EDIT - edit the entry in the electronic catalogue
        ///DELETE - delete a book entry from the electronic catalog
        ///GET - get a list of books from the electronic catalog (filters are available)
        ///EXPORT_XML - export an electronic catalog to an xml file
        ///EXPORT_JSON - export an electronic catalog to a json file
        ///EXPORT_BINARY - export electronic catalog in the dat file
        ///IMPORT_XML - import books from an xml file into an electronic catalog
        ///IMPORT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommandsDescription {
            get {
                return ResourceManager.GetString("CommandsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To add a book to the catalog, you must specify the ISBN code of the book.
        /// </summary>
        internal static string EditMandatory {
            get {
                return ResourceManager.GetString("EditMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while executing the program. Error description:.
        /// </summary>
        internal static string ExceptionIntro {
            get {
                return ResourceManager.GetString("ExceptionIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to file has done.
        /// </summary>
        internal static string ExportDone {
            get {
                return ResourceManager.GetString("ExportDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from the file has done.
        /// </summary>
        internal static string ImportDone {
            get {
                return ResourceManager.GetString("ImportDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of books from the catalog on request.
        /// </summary>
        internal static string ShortList {
            get {
                return ResourceManager.GetString("ShortList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have launched a program to manage the electronic catalog of your books..
        /// </summary>
        internal static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
